/**
 *@author huangdongxu
 *@Date Nov 22, 2017
*/

/**
 * 
 * @apiDefine Unauthorized
 * @apiError 401 Unauthorized
 * @apiErrorExample {json} Error-Response
 *  HTTP/1.1 401 Unauthorized
 *     
 */
/**
 * 
 * @apiDefine Success
 * @apiSuccess {int} code represent process status
 * @apiSuccess {String} message prompt message
 * @apiSuccess {Object} data which used to be represented in front-end

 *     
 */
/**
 * 
 * @apiDefine Header
 * @apiHeader {String}  Authorization authorization token
 * @apiHeaderExample {String} Header-Example:
 * Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3Misdsad
 *     
 */


package org.davingci.api;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.ws.rs.FormParam;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;

import org.davingci.annotation.Secured;
import org.davingci.dao.HibernateDao;
import org.davingci.pojo.Blog;
import org.davingci.pojo.View;
import org.davingci.security.AuthPrincipal;
import org.davingci.util.CalendarUtil;
import org.davingci.util.ResponseUtil;

@Path("/blog")
public class BlogApi {

	@Context
    SecurityContext securityContext;	

	/**
	 * @api {post} /blog/add Add Blog
	 * @apiVersion 0.1.0
	 * @apiName AddBlog
	 * @apiGroup Blog
	 * @apiPermission authorization
	 * @apiDescription add blog
	 * 
	 * @apiUse Header
	 * @apiParam {String} title blog title
	 * @apiParam {String} html html content, usually generated by editor in(for example, ckeditor,Editor.md) front-end.
	 * @apiParam {String} markdown markdown content if you use markdown editor in front-end, if not, it should be "" 
	 * @apiParam {String="htmlEditor","markdownEditor"} blogEditor the editor which you used in front-end. The value should be htmlEditor or markdownEditor.
	 
	 * @apiUse Success
	 * @apiSuccessExample Success-Response:
	 *     HTTP/1.1 200 OK
	 *     {
	 *       "code": 200,
	 *       "message": "publish blog success.",
	 *       "data":""
	 *     }
	 
	 * @apiUse Unauthorized
	 */
	@Secured
	@POST
	@Path("/add")
	@Produces(MediaType.APPLICATION_JSON+ ";charset=utf-8")
	public Response add(@FormParam("title") String title, 
						@FormParam("html") String html,
						@FormParam("markdown") String markdown,
						@FormParam("blogEditor") String blogEditor) {
		
		Date createAt = CalendarUtil.getNow();
		Date lastModifyAt = CalendarUtil.getNow();
		
		AuthPrincipal principal = (AuthPrincipal) securityContext.getUserPrincipal();

	    String username = principal.getUsername();
	    int userId = principal.getUserId();
	    
	    //TODO
	    //Extra content from html
	    //index with ElasticSearch
		
		Blog blog = new Blog.BlogBuilder()
							.title(title)
							.markdown(markdown)
							.html(html)
							.blogEditor(blogEditor)
							.userId(userId)
							.username(username)
							.createAt(createAt)
							.lastModifyAt(lastModifyAt)
							.build();
		HibernateDao dao = new HibernateDao();
		dao.add(blog);
		
		
		
		ResponseUtil ru = new ResponseUtil();
		ru.code(200).message("publish blog success.");
		return Response.status(200).entity(ru).build();
	}
	
	/**
	 * @api {post} /blog/update Update Blog
	 * @apiVersion 0.1.0
	 * @apiName UpdateBlog
	 * @apiGroup Blog
	 * @apiPermission authorization
	 * @apiDescription update blog
	
	 * @apiUse Header
	 * @apiParam {String} title blog title
	 * @apiParam {String} html html content, usually generated by editor in(for example, ckeditor,Editor.md) front-end.
	 * @apiParam {String} markdown markdown content if you use markdown editor in front-end, if not, it should be "" 
	 * @apiParam {String} blogId the id of the blog which you would like to update.
	 
	 * @apiUse Success
	 * @apiSuccessExample Update Success:
	 *     HTTP/1.1 200 OK
	 *     {
	 *       "code": 200,
	 *       "message": "update blog success.",
	 *       "data":""
	 *     }
	 * @apiSuccessExample Update Failure:
	 *     HTTP/1.1 200 OK
	 *     {
	 *       "code": 201,
	 *       "message": "blogId is incorrect.",
	 *       "data":""
	 *     }
	 * @apiUse Unauthorized
	 */
	@Secured
	@POST
	@Path("/update")
	@Produces(MediaType.APPLICATION_JSON+ ";charset=utf-8")
	public Response add(@FormParam("title") String title, 
						@FormParam("html") String html,
						@FormParam("markdown") String markdown,
						@FormParam("blogId") int blogId) {
		
		Date lastModifyAt = CalendarUtil.getNow();
		
		HibernateDao dao = new HibernateDao();
		Blog blog = (Blog) dao.findById(Blog.class, blogId);
		
		ResponseUtil ru = new ResponseUtil();
		
		if(blog != null) {
			blog.setTitle(title);
			blog.setHtml(html);
			blog.setMarkdown(markdown);
			blog.setLastModifyAt(lastModifyAt);
			dao.update(blog);		
			ru.code(200).message("update blog success.");
			
		}
		else {
			ru.code(201).message("blogId is incorrect.");
			
		}
		return Response.status(200).entity(ru).build();
	}
	
	/**
	 * @api {get} /blog/get/{blogId} Get Blog
	 * @apiVersion 0.1.0
	 * @apiName GetBlog
	 * @apiGroup Blog
	 * @apiPermission all
	 * @apiDescription get blog
	
	 * @apiParam {String} blogId the id of the blog which you would like to get

	 * @apiUse Success
	 * @apiSuccessExample Get Success:
		HTTP/1.1 200 OK
		{
		    "code": 200,
		    "data": {
		        "blogEditor": "",
		        "blogId": 1,
		        "createAt": 1510306770000,
		        "favouriteCount": 0,
		        "html": "",
		        "lastModifyAt": 1510820764000,
		        "markCount": 0,
		        "markdown": "",
		        "title": "huangdongxu's second blog",
		        "userId": 1,
		        "username": "huangdongxu",
		        "viewCount": 4
		    },
		    "message": "get blog success."
		} 
	 * @apiSuccessExample Can't Get Blog:
	 *     HTTP/1.1 200 OK
	 *     {
	 *       "code": 201,
	 *       "message": "blogId is incorrect or blog has been deleted",
	 *       "data":""
	 *     }
	 */
	/**
	 * get the blog
	 * insert view into view table
	 * update blog viewCount in blog table
	 * return blog
	 * @param blogId
	 * @return
	 */
	@GET
	@Path("/get/{blogId}")
	@Produces(MediaType.APPLICATION_JSON+ ";charset=utf-8")
	public Response get(@PathParam("blogId") int blogId) {

		ResponseUtil ru = new ResponseUtil();
		HibernateDao dao = new HibernateDao();
		Blog blog = (Blog) dao.findById(Blog.class, blogId);
		if(blog != null) {
			
			//get blog, add view
			int authorId = blog.getUserId();
			

		   
		    int viewUserId = -1;
			Date createAt = CalendarUtil.getNow();
			View view = new View();
			view.authorId(authorId).blogId(blogId).viewUserId(viewUserId).createAt(createAt);
			dao.add(view);
			
			//update blog views
			blog.setViewCount(blog.getViewCount()+1);
			dao.update(blog);
			
			ru.code(200).message("get blog success.").data(blog);
			
		}
		else {
			ru.code(201).message("blogId is incorrect or blog has been deleted");
			
		}
		return Response.status(200).entity(ru).build();
	}
	
	
	/**
	 * @api {post} /blog/delete Delete Blog
	 * @apiVersion 0.1.0
	 * @apiName DeleteBlog
	 * @apiGroup Blog
	 * @apiPermission authorization
	 * @apiDescription delete blog
	
	 * @apiUse Header
	 * @apiParam {String} blogId the id of blog which you would like to delete
	 
	 * @apiUse Success
	 * @apiSuccessExample Delete Success:
	 *     HTTP/1.1 200 OK
	 *     {
	 *       "code": 200,
	 *       "message": "delete blog success.",
	 *       "data":""
	 *     }
	 * @apiSuccessExample Delete Failure:
	 *     HTTP/1.1 200 OK
	 *     {
	 *       "code": 201,
	 *       "message": "blogId is incorrect.",
	 *       "data":""
	 *     }
	 * @apiUse Unauthorized
	 */
	@Secured
	@POST
	@Path("/delete")
	@Produces(MediaType.APPLICATION_JSON+ ";charset=utf-8")
	public Response delete(@FormParam("blogId") int blogId) {
		ResponseUtil ru = new ResponseUtil();
		HibernateDao dao = new HibernateDao();
		Blog blog = (Blog) dao.findById(Blog.class, blogId);
		if(blog != null) {
			dao.delete(blog);
			ru.code(200).message("delete blog success.");
			
		}
		else {
			ru.code(201).message("blogId is incorrect.");
			
		}
		return Response.status(200).entity(ru).build();
		
	}
	
	/**
	 * @api {post} /blog/query Query Blog
	 * @apiVersion 0.1.0
	 * @apiName QueryBlog
	 * @apiGroup Blog
	 * @apiPermission all
	 * @apiDescription query blog by createTime
	
	 * @apiParam {String} startTime the bolgs should be created after the startTime
	 * @apiParam {String} endTime endTime the blogs should be created before the endTime
	 * @apiParamExample {String} Request-Example:
	 * startTime:"2017-11-09",
	 * endTime:"2017-11-20",
	 * @apiUse Success
	 * @apiSuccessExample Query Success:
		HTTP/1.1 200 OK
		{
		    "code": 200,
		    "data": [
		        {
		            "blogEditor": "",
		            "blogId": 2,
		            "createAt": 1510934967000,
		            "favouriteCount": 1,
		            "html": "",
		            "lastModifyAt": 1510934967000,
		            "markCount": 1,
		            "markdown": "",
		            "title": "admin",
		            "userId": 1,
		            "username": "huangdongxu",
		            "viewCount": 0
		        },
		        {
		            "blogEditor": "",
		            "blogId": 4,
		            "createAt": 1510944250000,
		            "favouriteCount": 0,
		            "html": "<html><p>admimi</p></html>",
		            "lastModifyAt": 1511365630000,
		            "markCount": 0,
		            "markdown": "",
		            "title": "admim",
		            "userId": 1,
		            "username": "huangdongxu",
		            "viewCount": 0
		        }
		    ],
		    "message": "success."
		} 
	*/
	@POST
	@Path("/query")
	@Produces(MediaType.APPLICATION_JSON+ ";charset=utf-8")
	public Response query(@FormParam("startTime") String startTime, @FormParam("endTime") String endTime) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		Date startDate = new Date();
		Date endDate = new Date();
		try {
			startDate = sdf.parse(startTime);
			endDate = sdf.parse(endTime);
		} catch (ParseException e) {
			
			e.printStackTrace();
		}
		ArrayList<Date> list = new ArrayList<Date>();
		list.add(startDate);
		list.add(endDate);
		
		HibernateDao dao = new HibernateDao();
		String hql = "FROM Blog B WHERE B.createAt between ? and ?";
		List<?> blogs = dao.findByHQL(hql,list);
		
		
		
		ResponseUtil ru = new ResponseUtil();
		ru.code(200).message("success.").data(blogs);
		return Response.status(200).entity(ru).build();
	}
}
